INSTALL_BLOCKS = {
    'crm' : [
        (32, 'mail'),
        (156, 'base_action_rule'),
        (72, 'fetchmail'),
        (83, 'calendar'),
        (134, 'portal'),
        (136, 'crm'),
        (207, 'auth_signup'),
        (189, 'im_odoo_support'),
        (282, 'sales_team'),
        (56, 'resource'),
        (109, 'marketing'),
        (176, 'bus'),
        (230, 'base_setup'),
        (248, 'utm'),
        (267, 'mail_tip'),
    ],
    'projects' : [
        (72, 'fetchmail'),
        (32, 'mail'),
        (251, 'product'),
        (134, 'portal'),
        (232, 'procurement'),
        (25, 'analytic'),
        (56, 'resource'),
        (117, 'decimal_precision'),
        (176, 'bus'),
        (230, 'base_setup'),
        (201, 'project'),
        (267, 'mail_tip'),
        (207, 'auth_signup'),
        (189, 'im_odoo_support'),
    ],
    'website builder' : [
        (212, 'website'),
        (91, 'website_theme_install'),
    ],
    'blogs' : [

        (171, 'website'),
        (188, 'im_odoo_support'),
        (228, 'website_blog'),
        (25, 'analytic'),
        (31, 'mail'),
        (70, 'fetchmail'),
        (53, 'website_mail'),
        (86, 'website_theme_install'),
        (200, 'project'),
        (266, 'mail_tip'),
        (277, 'procurement'),
        (17, 'resource'),
        (110, 'decimal_precision'),
        (175, 'bus'),
        (230, 'base_setup'),
        (84, 'website_partner'),
        (128, 'portal'),
        (206, 'auth_signup'),
        (249, 'product'),
    ],
    'sales management' : [

        (171, 'website'),
        (188, 'im_odoo_support'),
        (228, 'website_blog'),
        (25, 'analytic'),
        (31, 'mail'),
        (70, 'fetchmail'),
        (189, 'account'),
        (53, 'website_mail'),
        (86, 'website_theme_install'),
        (168, 'sale'),
        (277, 'procurement'),
        (151, 'barcodes'),
        (17, 'resource'),
        (37, 'portal_sale'),
        (110, 'decimal_precision'),
        (175, 'bus'),
        (230, 'base_setup'),
        (200, 'project'),
        (266, 'mail_tip'),
        (247, 'stock'),
        (8, 'account_full_reconcile'),
        (84, 'website_partner'),
        (104, 'payment_transfer'),
        (128, 'portal'),
        (133, 'account_bank_statement_import'),
        (160, 'payment'),
        (206, 'auth_signup'),
        (249, 'product'),
        (282, 'sales_team'),
    ],
    'point of sale' : [
        (271, 'web_planner'),
        (23, 'web_tip'),
        (257, 'web_view_editor'),
        (280, 'web_kanban_gauge'),
        (91, 'web_settings_dashboard'),
        (25, 'analytic'),
        (266, 'mail_tip'),
        (249, 'product'),
        (128, 'portal'),
        (31, 'mail'),
        (110, 'decimal_precision'),
        (175, 'bus'),
        (230, 'base_setup'),
        (189, 'account'),
        (151, 'barcodes'),
        (206, 'auth_signup'),
	(70, 'fetchmail'),
	(188, 'im_odoo_support'),
	(37, 'portal_sale'),
	(248, 'portal_stock'),
	(277, 'procurement'),
	(160, 'payment'),
	(168, 'sale'),
	(247, 'stock'),
	(281, 'stock_account'),
	(34, 'sale_stock'),
	(75, 'point_of_sale'),
	(276, 'procurement_jit'),
	(48, 'report'),
	(90, 'web_editor'),
	(8, 'account_full_reconcile'),
	(104, 'payment_transfer'),
	(133, 'account_bank_statement_import'),
	(39, 'base_import'),
	(127, 'auth_crypt'),
	(100, 'web'),
	(109, 'web_calendar'),
	(190, 'web_diagram'),
	(198, 'web_kanban'),
	(105, 'base'),
	(282, 'sales_team'),
    ],
    'discuss' : [

        (188, 'im_odoo_support'),
        (31, 'mail'),
        (70, 'fetchmail'),
        (128, 'portal'),
        (206, 'auth_signup'),
        (175, 'bus'),
        (230, 'base_setup'),
        (266, 'mail_tip'),
    ],
    'invoicing' : [

        (189, 'account'),
        (160, 'payment'),
        (8, 'account_full_reconcile'),
        (104, 'payment_transfer'),
        (128, 'portal'),
        (133, 'account_bank_statement_import'),
        (206, 'auth_signup'),
        (249, 'product'),
        (175, 'bus'),
        (25, 'analytic'),
        (110, 'decimal_precision'),
        (230, 'base_setup'),
        (266, 'mail_tip'),
        (277, 'procurement'),
        (188, 'im_odoo_support'),
        (31, 'mail'),
        (70, 'fetchmail'),
    ],
    'mrp' : [

        (277, 'procurement'),
        (247, 'stock'),
        (273, 'mrp'),
        (25, 'analytic'),
        (17, 'resource'),
        (110, 'decimal_precision'),
        (175, 'bus'),
        (230, 'base_setup'),
        (266, 'mail_tip'),
        (31, 'mail'),
        (151, 'barcodes'),
        (189, 'account'),
        (70, 'fetchmail'),
        (188, 'im_odoo_support'),
        (8, 'account_full_reconcile'),
        (104, 'payment_transfer'),
        (128, 'portal'),
        (133, 'account_bank_statement_import'),
        (160, 'payment'),
        (206, 'auth_signup'),
        (249, 'product'),
        (281, 'stock_account'),
    ],
    'inventory management' : [

        (31, 'mail'),
        (151, 'barcodes'),
        (70, 'fetchmail'),
        (188, 'im_odoo_support'),
        (277, 'procurement'),
        (247, 'stock'),
        (128, 'portal'),
        (206, 'auth_signup'),
        (249, 'product'),
        (175, 'bus'),
        (110, 'decimal_precision'),
        (230, 'base_setup'),
        (266, 'mail_tip'),
    ],
    'accounting and finance ' : [

        (189, 'account'),
        (223, 'account_accountant'),
        (160, 'payment'),
        (8, 'account_full_reconcile'),
        (104, 'payment_transfer'),
        (128, 'portal'),
        (133, 'account_bank_statement_import'),
        (206, 'auth_signup'),
        (249, 'product'),
        (25, 'analytic'),
        (175, 'bus'),
        (110, 'decimal_precision'),
        (230, 'base_setup'),
        (266, 'mail_tip'),
        (277, 'procurement'),
        (31, 'mail'),
        (70, 'fetchmail'),
        (188, 'im_odoo_support'),
    ],
   'issue tracking' : [

        (254, 'project_issue'),
        (128, 'portal'),
        (206, 'auth_signup'),
        (249, 'product'),
        (282, 'sales_team'),
        (175, 'bus'),
        (25, 'analytic'),
        (17, 'resource'),
        (110, 'decimal_precision'),
        (200, 'project'),
        (230, 'base_setup'),
        (266, 'mail_tip'),
        (277, 'procurement'),
        (188, 'im_odoo_support'),
        (31, 'mail'),
        (70, 'fetchmail'),
    ],
    'productivity' : [

        (128, 'portal'),
        (206, 'auth_signup'),
        (175, 'bus'),
        (230, 'base_setup'),
        (266, 'mail_tip'),
        (188, 'im_odoo_support'),
        (31, 'mail'),
        (70, 'fetchmail'),
        (237, 'note'),
    ],
    'ecommerce' : [

        (31, 'mail'),
        (189, 'account'),
        (160, 'payment'),
        (168, 'sale'),
        (125, 'website_portal_sale'),
        (26, 'website_sale'),
        (37, 'portal_sale'),
        (175, 'bus'),
        (266, 'mail_tip'),
        (277, 'procurement'),
        (8, 'account_full_reconcile'),
        (2, 'rating'),
        (22, 'website_portal'),
        (86, 'website_theme_install'),
        (104, 'payment_transfer'),
        (128, 'portal'),
        (133, 'account_bank_statement_import'),
        (171, 'website'),
        (176, 'website_payment'),
        (206, 'auth_signup'),
        (249, 'product'),
        (282, 'sales_team'),
        (25, 'analytic'),
        (53, 'website_mail'),
        (110, 'decimal_precision'),
        (230, 'base_setup'),
        (70, 'fetchmail'),
        (188, 'im_odoo_support'),
    ],
    'purchase management' : [

        (247, 'stock'),
        (281, 'stock_account'),
        (268, 'purchase'),
        (8, 'account_full_reconcile'),
        (104, 'payment_transfer'),
        (128, 'portal'),
        (133, 'account_bank_statement_import'),
        (160, 'payment'),
        (206, 'auth_signup'),
        (249, 'product'),
        (175, 'bus'),
        (25, 'analytic'),
        (110, 'decimal_precision'),
        (230, 'base_setup'),
        (189, 'account'),
        (266, 'mail_tip'),
        (277, 'procurement'),
        (151, 'barcodes'),
        (31, 'mail'),
        (188, 'im_odoo_support'),
        (70, 'fetchmail'),
    ],
    'employee directory ' : [

        (31, 'mail'),
        (70, 'fetchmail'),
        (238, 'hr'),
        (128, 'portal'),
        (206, 'auth_signup'),
        (17, 'resource'),
        (175, 'bus'),
        (230, 'base_setup'),
        (266, 'mail_tip'),
        (188, 'im_odoo_support'),
    ],
    'timesheets' : [

        (189, 'account'),
        (202, 'hr_attendance'),
        (250, 'hr_timesheet'),
        (160, 'payment'),
        (231, 'hr_timesheet_sheet'),
        (8, 'account_full_reconcile'),
        (104, 'payment_transfer'),
        (128, 'portal'),
        (133, 'account_bank_statement_import'),
        (206, 'auth_signup'),
        (249, 'product'),
        (175, 'bus'),
        (25, 'analytic'),
        (17, 'resource'),
        (110, 'decimal_precision'),
        (230, 'base_setup'),
        (266, 'mail_tip'),
        (277, 'procurement'),
        (31, 'mail'),
        (188, 'im_odoo_support'),
        (70, 'fetchmail'),
        (238, 'hr'),
    ],
    'recruitment process ' : [

        (31, 'mail'),
        (89, 'base_action_rule'),
        (238, 'hr'),
        (188, 'im_odoo_support'),
        (124, 'survey'),
        (78, 'calendar'),
        (59, 'hr_recruitment'),
        (53, 'website_mail'),
        (102, 'marketing'),
        (175, 'bus'),
        (230, 'base_setup'),
        (266, 'mail_tip'),
        (128, 'portal'),
        (206, 'auth_signup'),
        (17, 'resource'),
        (110, 'decimal_precision'),
        (199, 'utm'),
        (171, 'website'),
        (184, 'document'),
        (86, 'website_theme_install'),
        (70, 'fetchmail'),
    ],
    'expense tracker' : [

        (189, 'account'),
        (212, 'hr_contract'),
        (277, 'procurement'),
        (223, 'account_accountant'),
        (160, 'payment'),
        (38, 'hr_expense'),
        (25, 'analytic'),
        (17, 'resource'),
        (110, 'decimal_precision'),
        (175, 'bus'),
        (230, 'base_setup'),
        (266, 'mail_tip'),
        (70, 'fetchmail'),
        (188, 'im_odoo_support'),
        (31, 'mail'),
        (89, 'base_action_rule'),
        (238, 'hr'),
        (8, 'account_full_reconcile'),
        (104, 'payment_transfer'),
        (128, 'portal'),
        (133, 'account_bank_statement_import'),
        (206, 'auth_signup'),
        (249, 'product'),
    ],
    'dashboards' : [

        (170, 'board'),
    ],
    'survey' : [

        (188, 'im_odoo_support'),
        (171, 'website'),
        (31, 'mail'),
        (70, 'fetchmail'),
        (124, 'survey'),
        (53, 'website_mail'),
        (102, 'marketing'),
        (175, 'bus'),
        (230, 'base_setup'),
        (266, 'mail_tip'),
        (86, 'website_theme_install'),
        (128, 'portal'),
        (206, 'auth_signup'),
        (199, 'utm'),
    ],
    'mass mailing campaigns' : [

        (188, 'im_odoo_support'),
        (31, 'mail'),
        (70, 'fetchmail'),
        (83, 'mass_mailing'),
        (103, 'link_tracker'),
        (128, 'portal'),
        (206, 'auth_signup'),
        (175, 'bus'),
        (102, 'marketing'),
        (230, 'base_setup'),
        (199, 'utm'),
        (266, 'mail_tip'),
    ],
    'lunch' : [

        (45, 'lunch'),
        (110, 'decimal_precision'),
    ],
    'equipments' : [

        (31, 'mail'),
        (70, 'fetchmail'),
        (238, 'hr'),
        (188, 'im_odoo_support'),
        (215, 'hr_equipment'),
        (128, 'portal'),
        (206, 'auth_signup'),
        (17, 'resource'),
        (175, 'bus'),
        (230, 'base_setup'),
        (266, 'mail_tip'),
    ],
    'calendar' : [

        (31, 'mail'),
        (89, 'base_action_rule'),
        (70, 'fetchmail'),
        (188, 'im_odoo_support'),
        (78, 'calendar'),
        (128, 'portal'),
        (206, 'auth_signup'),
        (17, 'resource'),
        (175, 'bus'),
        (230, 'base_setup'),
        (266, 'mail_tip'),
    ],
    'online events' : [

        (31, 'mail'),
        (171, 'website'),
        (86, 'website_theme_install'),
        (80, 'event'),
        (70, 'fetchmail'),
        (188, 'im_odoo_support'),
        (3, 'website_event'),
        (84, 'website_partner'),
        (128, 'portal'),
        (206, 'auth_signup'),
        (175, 'bus'),
        (102, 'marketing'),
        (53, 'website_mail'),
        (230, 'base_setup'),
        (199, 'utm'),
        (266, 'mail_tip'),
    ],
    'slides' : [

        (31, 'mail'),
        (53, 'website_mail'),
        (171, 'website'),
        (86, 'website_theme_install'),
        (70, 'fetchmail'),
        (188, 'im_odoo_support'),
        (88, 'website_slides'),
        (102, 'marketing'),
        (175, 'bus'),
        (230, 'base_setup'),
        (266, 'mail_tip'),
        (128, 'portal'),
        (206, 'auth_signup'),
        (199, 'utm'),
    ],
    'forum' : [

        (31, 'mail'),
        (171, 'website'),
        (86, 'website_theme_install'),
        (70, 'fetchmail'),
        (92, 'gamification'),
        (188, 'im_odoo_support'),
        (187, 'website_forum'),
        (53, 'website_mail'),
        (175, 'bus'),
        (266, 'mail_tip'),
        (274, 'portal_gamification'),
        (84, 'website_partner'),
        (128, 'portal'),
        (206, 'auth_signup'),
        (230, 'base_setup'),
    ],
    'fleet management' : [

        (70, 'fetchmail'),
        (31, 'mail'),
        (71, 'fleet'),
        (188, 'im_odoo_support'),
        (128, 'portal'),
        (206, 'auth_signup'),
        (175, 'bus'),
        (230, 'base_setup'),
        (266, 'mail_tip'),
    ],
    'website live chat ' : [

        (2, 'rating'),
        (128, 'portal'),
        (206, 'auth_signup'),
        (175, 'bus'),
        (230, 'base_setup'),
        (266, 'mail_tip'),
        (31, 'mail'),
        (70, 'fetchmail'),
        (188, 'im_odoo_support'),
        (94, 'im_livechat'),
    ],
    'repairs management' : [

        (70, 'fetchmail'),
        (168, 'sale'),
        (247, 'stock'),
        (37, 'portal_sale'),
        (281, 'stock_account'),
        (248, 'portal_stock'),
        (276, 'procurement_jit'),
        (8, 'account_full_reconcile'),
        (44, 'mrp_repair'),
        (104, 'payment_transfer'),
        (128, 'portal'),
        (133, 'account_bank_statement_import'),
        (160, 'payment'),
        (206, 'auth_signup'),
        (249, 'product'),
        (282, 'sales_team'),
        (34, 'sale_stock'),
        (175, 'bus'),
        (25, 'analytic'),
        (110, 'decimal_precision'),
        (230, 'base_setup'),
        (266, 'mail_tip'),
        (189, 'account'),
        (277, 'procurement'),
        (151, 'barcodes'),
        (188, 'im_odoo_support'),
        (31, 'mail'),
    ],
    'Authentication via LDAP':[(65, 'auth_ldap'),],
    'Decimal Precision' : [(113, 'decimal_precision'),],

}
